### ISSUE TITLE
Unable to add external files

### ISSUE THREAD

**Issue by TestBuildMac** [maltfield/cross-platform-python-gui#6] opened 2020-09-26 08:55 UTC
**builDmg.sh**

```
# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import copy_metadata, collect_data_files

datas = collect_data_files('grpc')
datas += copy_metadata('google-cloud-core')
datas += copy_metadata('google-cloud-firestore')
datas += copy_metadata('google-api-core')
datas += copy_metadata('google-api-core')
datas += copy_metadata('firebase-admin')
datas += [
    ("../src/data/locales/en/LC_MESSAGES/KivyMDCollection.mo", "../src/data/locales/en/LC_MESSAGES"),
    ("../src/data/locales/ru/LC_MESSAGES/KivyMDCollection.mo", "../src/data/locales/ru/LC_MESSAGES"),
    ("../src/data/fonts/DejaVuSans/DejaVuSansCondensed-Bold.ttf", "../src/data/fonts/DejaVuSans"),
    ("../src/data/fonts/DejaVuSans/DejaVuSansCondensed-Regular.ttf", "../src/data/fonts/DejaVuSans"),
    ("../src/data/fonts/JetBrainsMono-1.0.0/JetBrainsMono-Regular.ttf", "../src/data/fonts/JetBrainsMono-1.0.0"),
    ("../src/data/base.json", "../src/data"),
    ("../src/data/LICENSE-en.txt", "../src/data"),
    ("../src/data/LICENSE-ru.txt", "../src/data"),
    ("../src/data/REG-INFO-en.txt", "../src/data"),
    ("../src/data/REG-INFO-ru.txt", "../src/data"),
    ("../src/data/version.txt", "../src/data"),
]
block_cipher = None

a = Analysis(
    ['../src/main.py'],
    pathex=['./'],
    binaries=[],
    datas=datas,
    hiddenimports=['pkg_resources.py2_warn'],
    hookspath=[],
    runtime_hooks=[],
    excludes=['_tkinter', 'Tkinter', 'enchant', 'twisted'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='${APP_NAME}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False
)
coll = COLLECT(
    exe, Tree('../src/'),
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='${APP_NAME}'
)
app = BUNDLE(
    coll,
    name='${APP_NAME}.app',
    icon=None,
    bundle_identifier=None
)
```

All attempts to include external files in the package...

![Снимок экрана 2020-09-26 в 11 42 53](https://user-images.githubusercontent.com/71851236/94336748-063a3a00-ffee-11ea-8186-9d1a696d9c51.png)

...fail:

![Снимок экрана 2020-09-26 в 11 37 50](https://user-images.githubusercontent.com/71851236/94336763-2b2ead00-ffee-11ea-9b0f-69bcbb53b3c5.png)
![Снимок экрана 2020-09-26 в 11 38 28](https://user-images.githubusercontent.com/71851236/94336764-2d910700-ffee-11ea-9727-60d078a8f3a8.png)

I've tried specifying paths to the `data` folder in different ways, but that doesn't give any results. If you remove the addition of external files from the spec file...

![Снимок экрана 2020-09-26 в 11 42 53](https://user-images.githubusercontent.com/71851236/94336828-adb76c80-ffee-11ea-8a16-bee0263ed5ec.png)

...the package builds successfully.

Here is the structure of my project:

![Снимок экрана 2020-09-26 в 11 54 37](https://user-images.githubusercontent.com/71851236/94336901-36cea380-ffef-11ea-9467-28b9b7571eb2.png)

**Comment by maltfield** [comment] 2020-09-27 12:29
Hi @TestBuildMac, I believe the issue is with the second argument in your tuples. If you change them all to `'.'`, do the files get built-in? For example, try this:

```
datas += [
    ("../src/data/locales/en/LC_MESSAGES/KivyMDCollection.mo", "."),
    ("../src/data/locales/ru/LC_MESSAGES/KivyMDCollection.mo", "."),
    ("../src/data/fonts/DejaVuSans/DejaVuSansCondensed-Bold.ttf", "."),
...
```

See how I do this to package two files into my MacOS builds with my downstream project here:

 * https://github.com/BusKill/buskill-app/blob/74916292bf5b78db81bc8b424f1155fd8080a195/build/mac/buildDmg.sh#L208

If I understand this correctly, this isn't a bug related to what I've built with this repo so much as just PyInstaller learning curve confusion. See the relevant documentation here:

 * https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-data-files

I'm closing this issue for now, but if this is in-fact a bug with this `cross-platform-python-gui` repo, please let me know

**Closed as completed by maltfield** 2020-09-27 12:29 UTC
