### ISSUE TITLE
helloWorld.AppImage not working

### ISSUE THREAD

**Issue by emanuele** [maltfield/cross-platform-python-gui#4] opened 2020-09-05 18:02 UTC
Hi,

Thank you for the great project!
I tried to execute the pre-built hello world application for Linux on Ubuntu 18.04, specifically "Public Build Artifact: Linux 236469280" but I get the following error:
```
/tmp> ./helloWorld.AppImage 
/tmp/.mount_helloWtLQxIL/AppRun: line 37: /tmp/.mount_helloWtLQxIL/opt/python3.7/bin/python3.7: No such file or directory
```
What could be the problem?

Best,

Emanuele

**Comment by maltfield** [comment] 2020-09-05 18:23
thanks for the report :)

I cannot reproduce this on Debian 10. Can you please execute the following and post the output here?

```
cat /etc/issue
uname -a
which python
python --version
which python3
python3 --version
dpkg -l | grep -i python

./helloWorld.AppImage --appimage-extract
ls squashfs-root/opt/python3.7/bin/
ls squashfs-root/opt/python3.7/
ls squashfs-root/opt/
ls squashfs-root/
squashfs-root/AppRun
```

Also, are you executing in any sort of cloud environment or with a modified or virtualized kernel that may cause issues with fuse or loading kernel modules?

**Comment by emanuele** [comment] 2020-09-05 21:45
I had a look at the logs produced by your commands and found the issue: `/usr/bin/python3.7` was missing in my Ubuntu 18.04 (my python3 is v3.6.9) and your `squashfs-root/opt/python3.7/bin/python -> /usr/bin/python3.7` was symlinking it - so... broken link!

Solved with `apt install python3.7`.

Is python3.7 necessary or another python3.x is equally OK?

**Comment by maltfield** [comment] 2020-09-06 06:59
Actually, python being broken on your system should not affect this AppImage.

In fact, the whole point of the AppImage is that it's a self-contained executable; you should not have to have python installed on your system at all.

You did point out a bug that I believe was fixed in https://github.com/maltfield/cross-platform-python-gui/commit/7ad1851fe9e566d5431b312584bea1b1d357deb8

I don't know if it's possible to put your system in the state it was before (without python3.7 installed?) and try out the latest build to confirm that it works (while 236469280 does not)?

 * https://github.com/maltfield/cross-platform-python-gui/releases/tag/241416612_linux

**Comment by emanuele** [comment] 2020-09-06 07:36
Indeed it is possible, `apt` installed python3.7 in addition to the default python3.6. So `apt-get remove python3.7 python3.7-minimal` restored the initial situation.

I can confirm that your new build works perfectly!

Thank you for fixing the issue.

**Closed as completed** 2020-09-06 08:26 UTC
